name: Publish Package to npmjs
on:
  # keeping it purely manual for now as to not accidentally trigger a release
  #release:
  #  types: [published]
  workflow_dispatch:
    inputs:
      package:
        description: 'Package'
        required: true
        type: choice
        options:
          - '@reduxjs/toolkit'
          - '@rtk-query/codegen-openapi'
          - '@rtk-query/graphql-request-base-query'
          - '@reduxjs/rtk-codemods'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn workspace ${{ inputs.package }} test
      - run: yarn workspace ${{ inputs.package }} exec npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
